name: backend CI

#Executa sempre que houver um push para a branch main.
on:
  push:
    branches: [ "main" ]

jobs:
  #Constroi a imagem do Docker para o backend.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          cd backend
          npm install
      
      - name: Start Backend Server
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          TEST_ENV: ${{true}}
        run: |
          cd backend
          npm start > /dev/null 2>&1 &
          sleep 5
        
      - name: Run API Tests
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: |
          cd backend
          npm test
      
      - name: Build Docker Image
        run: |
          cd backend
          docker build -t backend
        working-directory: ./backend
