name: BackEnd Pipeline

#Executa sempre que houver um push para a branch main.
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  #Constroi a imagem do Docker para o backend.
  build:
    runs-on: ubuntu-latest
    #define a pasta de backend como padrão
    defaults:
      run:
        working-directory: ./backend
        
    #Importa váriaveis dos secrets
    env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          TEST_ENV: true
          PATRIMONIO_TESTE: ${{ secrets.PATRIMONIO_TESTE }}
          TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Instala as Dependencias da API
        run: npm install
      
      - name: Inicia o servidor da API
        run: |
          npm start > /dev/null 2>&1 &
          sleep 5

      - name: Roda os testes de API
        run: npm test

      - name: Constroi a imagem do docker
        run: docker build -t backend .

      - name: Deploy no Render
        if: success()
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        
